# Generated by Django 3.1.2 on 2020-11-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='title',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color'), ('package', 'package')], default='size', max_length=120),
        ),
    ]
